# Generated by Django 2.0.2 on 2018-03-18 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_auto_20180311_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField(max_length=10)),
                ('date', models.DateField(verbose_name='date published')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.register')),
            ],
        ),
    ]
